name: Build and Test

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: 
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checks out the repo
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Setup the environment
      run: |-
        bash setup.sh
    - name: Build and test groot
      run: |-
        mkdir build 
        cd build 
        cmake -DCODE_COVERAGE=ON -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug .. 
        cmake --build . --config Debug
        cp ../test/TestFiles/ test/ 
        ctest --output-on-failure --extra-verbose
